# This is a basic workflow to help you get started with Actions

name: Backend CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  test-backend:
    runs-on: ubuntu-latest  # Okolje, v katerem bo job tekel
    
    steps:
    - name: Checkout code  # Kloniranje repozitorija
      uses: actions/checkout@v3
    
    - name: Setup Node.js  # Namestitev Node.js okolja
      uses: actions/setup-node@v3
      with:
        node-version: 20
        
    - name: Install dependencies  # Namestitev odvisnosti
      run: |
        cd backend
        npm install
        
    - name: Run tests with coverage  # Izvajanje testov s pokritostjo
      run: |
        cd backend
        npm run test:ci
        
    - name: Upload coverage report  # Naložitev poročila o pokritosti
      uses: actions/upload-artifact@v3
      with:
        name: backend-coverage
        path: backend/coverage/
